# Generated by Django 5.1.7 on 2025-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captcha",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
